name: rainbow_edge_lighting
description: Animated rainbow edge lighting painter for Flutter widgets with smooth fade and disabled border blending.
version: 1.0.8
repository: https://github.com/vlcl753/rainbow_edge_lighting
homepage: https://github.com/vlcl753/rainbow_edge_lighting
issue_tracker: https://github.com/vlcl753/rainbow_edge_lighting/issues
topics:
  - animation
  - glow
  - effects
  - ui
  - painter



environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.22.0'

screenshots:
  - description: Rainbow edge lighting
    path: screenshots/rainbow_screen_shot.png
  - description: Rainbow edge lighting screen
    path: rainbow_screen.gif


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
# no assets needed